### ISSUE TITLE
Deux types de Visitor pour le même Visitable 

### ISSUE THREAD

**Issue by Eriwyr** [PolytechLyon/isi3-tp2-arbre-visiteur#1]
Nous n'arrivons pas à implémenter deux interfaces ou classes abstraites (VisitorAbsbtract / VisitorConcrete) qui héritent / implémentent Visitor. 

En effet, on voudrait utiliser pour les deux visiteurs la même classe Visitable, donc il faudrait avoir deux accept : accept(VisitorAbsbtract) et accept(VisitorConcrete). Celles-ci se répercuteraient sur Addition, Multiplication, etc ... alors qu'elles ne sont pas nécessaires à ces endroits.

Autrement, on pourrait n'avoir qu'une seule méthode accept(Node) dans Visitable. Mais dans ce cas, comment préciser au visiteur le type de ce que l'on souhaite visiter (OperatorBinaire au lieu de Node)?

Après quelques recherches, la seule solution que nous avons trouvée serait de faire deux fois le pattern Visitor. Cela nous ne semble pas plus efficace que d'avoir des visites similaires pour Addition et Multiplication par exemple. Est-ce la solution ? 

Je vous laisse en attaché un rapide UML illustrant nos réflexions. 

[Note 9 mars 2018 (1).pdf](https://github.com/PolytechLyon/isi3-tp2-arbre-visiteur/files/1797749/Note.9.mars.2018.1.pdf)

**Comment by Slashgear** [comment]
Votre raisonnement à du sens pour éviter de dupliquer addition et multiplication. on peut toujours passer par une méthode privée ;)

sinon on pourrait peutêtre s'en sortir avec des generic <>
